// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRZd_BIE1q0CN3XmmZBnn-wZNSm-qsv8',
    appId: '1:165880788591:android:67ca46610762106874bf9a',
    messagingSenderId: '165880788591',
    projectId: 'wildlife-tracker-af2be',
    storageBucket: 'wildlife-tracker-af2be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXm6zh66KfS46kXx30BL5Ztyfh_uDA_Rk',
    appId: '1:165880788591:ios:43b4d1bdf7327ce374bf9a',
    messagingSenderId: '165880788591',
    projectId: 'wildlife-tracker-af2be',
    storageBucket: 'wildlife-tracker-af2be.firebasestorage.app',
    iosClientId: '165880788591-kiaaijn4gbsu3kfcdfn9fusmglppbogf.apps.googleusercontent.com',
    iosBundleId: 'com.example.wildlifeTracker',
  );

}